### ISSUE TITLE
Setup and Use of plugins Alpha Branch for meta-url 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#26] opened 2021-08-12 17:01 UTC
https://github.com/OpenCPN/plugins/issues/381

Add to manual for devs

**Comment by rgleason** [comment] 2021-08-14 13:20
This is a good tool for Plugin Devs to use for testing their plugins on various platforms because 
1. Setting up your own meta-url allows  <username>/plugins/metadata Alpha branch updates to show in the PIM without having to make a PR to opencpn/plugins  Alpha branch and having bdbcat accept it. 
2. Tarballs do not need to be copied to multiple OS for testing. 
3. PIM system can be used on the Alpha catalog

This is a Plugin Developer technique that should be used more.

**Comment by leamas** [comment] 2021-08-15 11:07
Isn't this a duplicate of #15?

**Comment by rgleason** [comment] 2021-08-15 15:20
Yes. Tried to summarize advantages here

**Comment by rgleason** [comment] 2021-08-15 15:32
You can close if you wish.

**Comment by leamas** [comment] 2021-08-15 15:38
Perhaps you could close one of them, it's just that we don't should have duplicates..

**Closed** 2021-08-15 16:32 UTC
