### ISSUE TITLE
 Use of getPluginDataDir and GetpPrivateApplicationDataLocation() function #64 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#8] opened 2021-08-12 14:32 UTC
https://github.com/rgleason/LogbookKonni_pi/issues/6#issuecomment-830840789

and

https://github.com/OpenCPN/OpenCPN/issues/2256#issuecomment-831102613

**Comment by leamas** [comment] 2021-08-13 07:15
Isn't this a duplicate of #23?

**Comment by rgleason** [comment] 2021-08-13 10:43
Yes, the links are more detailed discussion and some work that could be used.
But closing.

**Comment by leamas** [comment] 2021-08-13 13:28
You didn't, but I do :)

**Closed by leamas** 2021-08-13 13:28 UTC
